# Test your FastAPI endpoints
### all users
GET http://127.0.0.1:8000/users/
Accept: application/json

### create user
POST http://127.0.0.1:8000/users/
Content-Type: application/json

{
  "email": "twc55@icloud.com",
  "password": "jndghkshgshgishgishdvmsosog"
}

### get user by id
GET http://127.0.0.1:8000/users/1/
Accept: application/json

###
